esphome:
  name: ble_tracker
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Catwoman"
  password: "qct25ssvfj97"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ble Tracker Fallback Hotspot"
    password: "mZzSr4mQYxur"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xrdzrtfsx&Rdq07"

ota:
  password: "xrdzrtfsx&Rdq07"

web_server:
  port: 80

esp32_ble_tracker:

text_sensor:
  - platform: ble_scanner
    name: "BLE Devices Scanner"
