esphome:
  name: 'garten_ventile'
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: 'Catwoman'
  password: 'qct25ssvfj97'
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.38
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: 'xrdzrtfsx&Rdq07'

ota:
  password: 'xrdzrtfsx&Rdq07'

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Ventil Button 1"
    id: button1
    on_press:
      then:
        - switch.toggle: garten_ventile_relay1
    # on_state:
    #   lambda: |-
    #     if (id(button1).state) {
    #       id(garten_ventile_relay1).turn_on();
    #     } else {
    #       id(garten_ventile_relay1).turn_off();
    #     }
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Ventil Button 2"
    id: button2
    on_press:
      then:
        - switch.toggle: garten_ventile_relay2
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "Ventil Button 3"
    id: button3
    on_press:
      then:
        - switch.toggle: garten_ventile_relay3
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "Ventil Button 4"
    id: button4
    on_press:
      then:
        - switch.toggle: garten_ventile_relay4
  - platform: status
    name: "Ventil Status"

switch:
  - platform: gpio
    name: "Ventil 1"
    pin: GPIO12
    id: garten_ventile_relay1
    restore_mode: RESTORE_DEFAULT_OFF
    interlock: &interlock_group [garten_ventile_relay1, garten_ventile_relay2, garten_ventile_relay3, garten_ventile_relay4]
  - platform: gpio
    name: "Ventil 2"
    pin: GPIO5
    id: garten_ventile_relay2
    interlock: *interlock_group
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Ventil 3"
    pin: GPIO4
    id: garten_ventile_relay3
    interlock: *interlock_group
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Ventil 4"
    pin: GPIO15
    id: garten_ventile_relay4
    interlock: *interlock_group
    restore_mode: RESTORE_DEFAULT_OFF


status_led:
  pin: GPIO13