esphome:
  name: "sonoff_valve_d"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Catwoman"
  password: "qct25ssvfj97"
  # manual_ip:
  # Set this to the IP of the ESP
  #static_ip: 192.168.8.108
  #gateway: 192.168.8.1
  # The subnet of the network. 255.255.255.0 works for most home networks.
  #subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "xrdzrtfsx&Rdq07"

ota:
  password: "xrdzrtfsx&Rdq07"

time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      inverted: true
    id: button
    on_press:
      then:
        # logic for cycling through movements: open->stop->close->stop->...
        - lambda: |
            if (id(valve).state == cover::COVER_OPEN) {
              if (id(openValve).state){
                // valve is in opening movement, stop it
                id(valve).stop();
              } else {
                // valve has finished opening, close it
                id(valve).close();
              }
            } else {
              if (id(closeValve).state){
                // valve is in closing movement, stop it
                id(valve).stop();
              } else {
                // valve has finished closing, open it
                id(valve).open();
              }
            }

switch:
  - platform: gpio
    pin: GPIO5
    id: openValve
  - platform: gpio
    pin: GPIO12
    id: closeValve

cover:
  - platform: template
    name: "Ventil"
    id: valve
    open_action:
      # cancel potential previous movement
      - switch.turn_off: closeValve
      # perform movement
      - switch.turn_on: openValve
      # wait until valve is open
      - delay: 20s
      # turn of relay to prevent keeping the motor powered
      - switch.turn_off: openValve
    close_action:
      - switch.turn_off: openValve
      - switch.turn_on: closeValve
      - delay: 20s
      - switch.turn_off: closeValve
    stop_action:
      - switch.turn_off: openValve
      - switch.turn_off: closeValve
    optimistic: True
    assumed_state: True
