- id: '1552989984242'
  alias: 'Büro: Sonne von Osten'
  trigger:
  - platform: webhook
    webhook_id: buero_sun_east
  condition: []
  action:
  - data:
      entity_id: cover.buro_bu_l_48
      position: 45
    service: cover.set_cover_position
  - data:
      entity_id: cover.buro_bu_r_45
      position: 100
    service: cover.set_cover_position
- id: '1552990638899'
  alias: 'Büro: Sonne von Süden'
  trigger:
  - platform: webhook
    webhook_id: buero_sun_south
  condition: []
  action:
  - data:
      entity_id: cover.buro_bu_l_48
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: cover.buro_bu_r_45
      position: 50
    service: cover.set_cover_position
- id: '1552990714355'
  alias: 'Büro: keine Sonne'
  trigger:
  - platform: webhook
    webhook_id: buero_no_sun
  condition: []
  action:
  - data:
      entity_id: cover.buro_bu_l_48
      position: 100
    service: cover.set_cover_position
  - data:
      entity_id: cover.buro_bu_r_45
      position: 100
    service: cover.set_cover_position
- id: '1558359638000'
  alias: Pumpen Timer Brunnen
  trigger:
  - entity_id: switch.pumpe_brunnen_relay
    platform: state
    to: 'on'
  action:
  - service: homeassistant.update_entity
    data:
      entity_id: input_number.timer_pumpe_brunnen
  - service: homeassistant.update_entity
    data:
      entity_id: binary_sensor.show_timer_brunnen
  - delay:
      minutes: '{{ states.input_number.timer_pumpe_brunnen.state | int }}'
  - data:
      entity_id: switch.pumpe_brunnen_relay
    service: switch.turn_off
- id: regner_garage
  alias: Regner Garage
  trigger:
  - entity_id: switch.ventil_1
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: input_boolean.bewaesserung_automation
    below: 1
  action:
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_rasen_garage.state | int }}'
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_1
    service: switch.turn_off
- id: wasser_terrasse
  alias: Wasser Terrasse
  trigger:
  - entity_id: switch.ventil_4
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: input_boolean.bewaesserung_automation
    below: 1
  action:
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_terrasse.state | int }}'
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_4
    service: switch.turn_off
- id: regner_hecken
  alias: Regner Hecken
  trigger:
  - entity_id: switch.ventil_3
    platform: state
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: input_boolean.bewaesserung_automation
    below: 1
  action:
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_hecken.state | int }}'
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_3
    service: switch.turn_off
- id: '1559545933689'
  alias: Brunnen Alarm
  trigger:
  - above: '200'
    below: '500'
    entity_id: sensor.pumpe_brunnen_leistung
    for: 00:03:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Brunnen läuft trocken
    service: notify.ios_mathiass_iphone
  - data:
      entity_id: switch.pumpe_brunnen_relay
    service: switch.turn_off
  - data:
      message: Brunnen läuft trocken
    service: notify.ios_julias_iphone
- id: set_automation_regner_state_on
  alias: Start Automatik
  trigger:
  - entity_id: input_boolean.bewaesserung_automation
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_number.status_automation_regner
      value: 1
    service: input_number.set_value
- id: set_automation_regner_state_off
  alias: Stop Automatik
  trigger:
  - entity_id: input_boolean.bewaesserung_automation
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: input_number.status_automation_regner
      value: 0
    service: input_number.set_value
- id: automation_regner_state_0
  alias: Regner Automatik Off
  trigger:
  - entity_id: input_number.status_automation_regner
    platform: numeric_state
    below: 1
  condition: []
  action:
  - data:
      entity_id: switch.ventil_1
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_2
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_3
    service: switch.turn_off
  - data:
      entity_id: switch.ventil_4
    service: switch.turn_off
  - data:
      entity_id: switch.pumpe_zisterne_relay
    service: switch.turn_off
- id: automation_regner_state_1
  alias: Regner Automatik 1 (Garage)
  trigger:
  - entity_id: input_number.status_automation_regner
    platform: numeric_state
    above: 0
    below: 2
  condition: []
  action:
  - data:
      entity_id: switch.ventil_1
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_rasen_garage.state | int }}'
  - data:
      entity_id: input_number.status_automation_regner
      value: 2
    service: input_number.set_value
- id: automation_regner_state_2
  alias: Regner Automatik 2
  trigger:
  - entity_id: input_number.status_automation_regner
    platform: numeric_state
    above: 1
    below: 3
  condition: []
  action:
  - data:
      entity_id: cover.cover_2
    service: cover.close_cover
  - data:
      entity_id: switch.ventil_4
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_terrasse.state | int }}'
  - data:
      entity_id: input_number.status_automation_regner
      value: 3
    service: input_number.set_value
- id: automation_regner_state_3
  alias: Regner Automatik 3
  trigger:
  - entity_id: input_number.status_automation_regner
    platform: numeric_state
    above: 2
    below: 4
  condition: []
  action:
  - data:
      entity_id: cover.cover_2
    service: cover.open_cover
  - delay: 00:00:10
  - data:
      entity_id: switch.ventil_3
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_hecken.state | int }}'
  - data:
      entity_id: input_number.status_automation_regner
      value: 4
    service: input_number.set_value
- id: automation_regner_state_4
  alias: Regner Automatik 4
  trigger:
  - entity_id: input_number.status_automation_regner
    platform: numeric_state
    above: 3
    below: 5
  condition: []
  action:
  - data:
      entity_id: cover.cover_2
    service: cover.close_cover
  - delay: 00:00:10
  - data:
      entity_id: switch.ventil_3
    service: switch.turn_on
  - delay:
      minutes: '{{ states.input_number.timer_hecken.state | int }}'
  - data:
      entity_id: input_number.status_automation_regner
      value: 0
    service: input_number.set_value
- id: '15595742978536'
  alias: Update Timers
  trigger:
  - hours: '*'
    minutes: '*'
    platform: time_pattern
    seconds: /30
  condition: []
  action:
  - data:
      entity_id:
      - sensor.timer_brunnen
      - sensor.timer_regner_garager
      - sensor.timer_regner_hecken
      - sensor.timer_wasser_terrasse
      - binary_sensor.show_timer_brunnen
      - binary_sensor.show_timer_regner_garager
      - binary_sensor.show_timer_regner_hecken
      - binary_sensor.show_timer_wasser_terrasse
    service: homeassistant.update_entity
