
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
some_password: welcome

wunderground_key: c26bd2ff8c511e8a

dark_sky_key: a6d3bad1e9edafc792d87d5af1fc4940

fibaro_user: mpneuried@googlemail.com
fibaro_pw: IjguutFT75kjgihgfi

influx_password: VnqLe5cqSX4ekE95rSVL


unifi_user: hassio
unifi_pw: 7sU78k2QtjJutxs8LL2a

neato_user: mpneuried@googlemail.com
neato_pw: BwXQILEkVs33JEmT

influx_user: hass
influx_pw: zpH9hXRaxtqMMd7NJ3WX

configurator_url: https://hassio.local/api/hassio_ingress/rQkq4QZjKCJkfa97nZsIgHHol3eW-leJKLQBg3NukJ4/